In [1]:
import numpy as np

**make numpy array from list**

In [2]:
myarr = np.array([3,21,23,37],np.int8)

In [3]:
myarr 

array([ 3, 21, 23, 37], dtype=int8)

**fetch first or any element**

In [4]:
myarr = np.array([3,21,23,37],np.int8)

In [5]:
myarr[0] 

3

**fetch row and column**

In [6]:
myarr = np.array([[3,21,23,37]],np.int8)

In [7]:
myarr[0,1] 

21

In [8]:
myarr = np.array([[3,21,23,37]],np.int8)

In [9]:
myarr[0,0]

3

**change item in list**

In [10]:
myarr = np.array([[3,21,23,37]],np.int8)

In [11]:
myarr[0,2]=50 

In [12]:
myarr

array([[ 3, 21, 50, 37]], dtype=int8)

**1:--array creation: convertion from other python structure**

In [13]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.ndim    #dimension means 2 bracket =2-D array

2

In [16]:
listarray.dtype     #datatype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
zeros=np.zeros((2,5))     #only make matrix of zero element

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng=np.arange(20)     #make 20 element from 0 to 19

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
lspace=np.linspace(1,5,12)

In [24]:
lspace        #1=first element, 5=last element, 12=from 1 to 5 in 12 times

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
lspace=np.linspace(1,3,4)

In [26]:
lspace

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [27]:
emp=np.empty((3,6))

In [28]:
emp      #make a random element for 3 row and 6 column matrix

array([[4.67296746e-307, 1.69121096e-306, 1.86919378e-306,
        1.86920057e-306, 7.56574003e-307, 6.23054972e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307, 9.79101082e-307, 1.78020576e-306],
       [1.69119873e-306, 2.22522868e-306, 1.24611809e-306,
        8.06632139e-308, 1.60221208e-306, 2.29178686e-312]])

In [29]:
ide=np.identity(5)        #make 4*4 identity matrix

In [30]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
ide.shape

(5, 5)

In [32]:
arange=np.arange(99)          #make 0 to 98 element 

In [33]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arange.reshape(3,33)       # 3*33=99, make make 3 row and 33 column matrix of 99 element

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arange.ravel()      #make 1-D array of reshape matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**NUMPY AXIS**

In [36]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x.sum(axis=0)   # SUM OF COLUMN

array([12, 15, 18])

In [39]:
x.sum(axis=1)

array([ 6, 15, 24])

In [40]:
for item in x.flat: #flat use for iteration
    print(item)

1
2
3
4
5
6
7
8
9


In [41]:
for i in x:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
for i in range(1,6):
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x.T #TRANSPOSE ARRAY

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
x.ndim #DIMENSION OF ARRAY

2

In [45]:
x.nbytes #कितना जगह(bytes) ले रहा है स्टोर करने के लिए

36

In [46]:
one=np.array([1,3,4,634,2])

In [47]:
one.argmax() #MAXIMUM ELEMENT

3

In [48]:
one.argmin() #MINIMUM ELEMENT

0

In [49]:
one.argsort()  #SORT INDICES IN ASSENDING ORDER

array([0, 4, 1, 2, 3], dtype=int64)

In [50]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
x.argmin()

0

In [52]:
x.argmax()

8

In [53]:
x.argmin(axis=0)    #MIN INDICES SHOW

array([0, 0, 0], dtype=int64)

In [54]:
x.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [55]:
x.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [56]:
x.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [57]:
x.argsort() #INDICES SORT

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [58]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [59]:
x.T #TRANSPOSE 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
x2=np.array([[2, 3, 1],
       [5, 9, 6],
       [4, 8,7]])

In [62]:
x2

array([[2, 3, 1],
       [5, 9, 6],
       [4, 8, 7]])

In [63]:
x+x2     #ARRAY X = ARRAY X2

array([[ 3,  5,  4],
       [ 9, 14, 12],
       [11, 16, 16]])

In [64]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
x2

array([[2, 3, 1],
       [5, 9, 6],
       [4, 8, 7]])

In [66]:
x-x2

array([[-1, -1,  2],
       [-1, -4,  0],
       [ 3,  0,  2]])

In [67]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
x2

array([[2, 3, 1],
       [5, 9, 6],
       [4, 8, 7]])

In [69]:
x*x2

array([[ 2,  6,  3],
       [20, 45, 36],
       [28, 64, 63]])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
x2

array([[2, 3, 1],
       [5, 9, 6],
       [4, 8, 7]])

In [72]:
x%x2

array([[1, 2, 0],
       [4, 5, 0],
       [3, 0, 2]])

In [73]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.sqrt(x)    #SQUARE ROOT OF X

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [75]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.where(x>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [77]:
type(np.where(x>5))

tuple

In [78]:
x2

array([[2, 3, 1],
       [5, 9, 6],
       [4, 8, 7]])

In [79]:
type(np.where(x2>4))

tuple

In [80]:
np.count_nonzero(x2)

9

In [81]:
import sys

In [82]:
py_ar=[1,4,55,3]

In [83]:
np_ar=np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)    #python size

112

In [85]:
np_ar.itemsize*np_ar.size  #NUMPY SIZE

16